import { TelegramChannel } from '../types';

export const TELEGRAM_CHANNELS_LIST: TelegramChannel[] = [
  {
    id: 'tg-spacetoon-tv',
    name: 'قناة سبيستون الأولى الرسمية',
    handle: '@SpacetoonTV',
    url: 'https://t.me/SpacetoonTV',
    webPreviewUrl: 'https://t.me/s/SpacetoonTV',
    type: 'channel',
    category: 'anime',
    badge: 'سبيستون كلاسيك ',
    description: 'القناة الشاملة لأعمال وذكريات سبيستون وكرتون زمان بجودة عالية وبدون إعلانات مزعجة وبدبلجة مركز الزهرة.',
    subscribersOrUsers: '+25K متابع نشط',
    featuredContent: ['شارة البداية الأصلية', 'أعمال سبيستون الذهبية', 'كونان، القناص، ريمي', 'جودة نقية 1080p'],
    isVerified: true,
    highlightColor: 'from-amber-500/20 to-yellow-600/20'
  },
  {
    id: 'tg-cartoonayamzman',
    name: 'كرتون أيام زمان (الجيل الذهبي)',
    handle: '@cartoonayamzman',
    url: 'https://t.me/cartoonayamzman',
    webPreviewUrl: 'https://t.me/s/cartoonayamzman',
    type: 'channel',
    category: 'anime',
    badge: 'كرتون الطيبين ',
    description: 'أرشيف كامل ونادر لمسلسلات الكرتون الكلاسيكية والمدبلجة من مركز الزهرة واستوديوهات الدبلجة العربية القديمة.',
    subscribersOrUsers: '+50K عضو نشط',
    featuredContent: ['كرتون الثمانينات والتسعينات', 'أنا وأخي، عهد الأصدقاء', 'دبلجة أصلية نادرة', 'تحميل ومشاهدة مباشرة'],
    isVerified: true,
    highlightColor: 'from-emerald-500/20 to-teal-600/20'
  },
  {
    id: 'tg-anime4up',
    name: 'شبكة وقناة ANIME4UP للأنمي',
    handle: '@Anime_4Up',
    url: 'https://t.me/Anime_4Up',
    webPreviewUrl: 'https://t.me/s/Anime_4Up',
    type: 'channel',
    category: 'anime',
    badge: 'أنمي ياباني مترجم ',
    description: 'أضخم قناة وتجمع لمتابعي ومحبي الأنمي الياباني، تغطية حصرية لكافة حلقات الموسم وأفلام الأنمي بأعلى جودة.',
    subscribersOrUsers: '+120K متابع نشط',
    featuredContent: ['أنميات الموسم المستمرة', 'هجوم العمالقة، ون بيس، جوجيتسو', 'أفلام أنمي كاملة', 'روابط تنزيل ومشاهدة سريعة'],
    isVerified: true,
    highlightColor: 'from-pink-500/20 to-rose-600/20'
  },
  {
    id: 'tg-conan-arabic',
    name: 'المحقق كونان - الحلقات والأفلام كاملة',
    handle: '@conan_arabic',
    url: 'https://t.me/conan_arabic',
    webPreviewUrl: 'https://t.me/s/conan_arabic',
    type: 'channel',
    category: 'anime',
    badge: 'المحقق كونان ',
    description: 'القناة الشاملة لكافة أجزاء وأفلام وحلقات المحقق كونان الخاصة المدبلجة والمترجمة بروابط سحابية مباشرة.',
    subscribersOrUsers: '+180K متابع نشط',
    featuredContent: ['جميع أفلام كونان السينمائية', 'أجزاء الدبلجة العربية', 'الحلقات الخاصة والأوفا', 'جودة Full HD'],
    isVerified: true,
    highlightColor: 'from-sky-500/20 to-blue-700/20'
  },
  {
    id: 'tg-koshk-aflam',
    name: 'كُشك أفلام السينما العالمية (Box Office)',
    handle: '@ggigg090',
    url: 'https://t.me/ggigg090',
    webPreviewUrl: 'https://t.me/s/ggigg090',
    type: 'channel',
    category: 'movies',
    badge: 'سينما عالمية ',
    description: 'مكتبة ضخمة مرتبة تضم روائع أفلام هوليوود، الأكشن، الغموض، والخيال العلمي بجودة بلوراي 1080p و 4K.',
    subscribersOrUsers: '+95K مشترك نشط',
    featuredContent: ['أفلام حديثة وكلاسيكية', 'سلاسل كريستوفر نولان', 'أفلام حائزة على الأوسكار', 'ملفات تحميل مباشرة'],
    isVerified: true,
    highlightColor: 'from-amber-600/20 to-orange-700/20'
  },
  {
    id: 'tg-netflix-arabic',
    name: 'قناة NET-FLIX العربية للمسلسلات والأفلام',
    handle: '@NetFlix_Arabic',
    url: 'https://t.me/NetFlix_Arabic',
    webPreviewUrl: 'https://t.me/s/NetFlix_Arabic',
    type: 'channel',
    category: 'netflix',
    badge: 'عروض نتفلكس ',
    description: 'تغطية يومية لأحدث مسلسلات وأفلام شبكة نتفلكس والمنصات العالمية مترجمة ومدبلجة للعربية بدقة فائقة.',
    subscribersOrUsers: '+140K متابع نشط',
    featuredContent: ['مسلسلات نتفلكس الحصرية', 'Breaking Bad، Stranger Things', 'أفلام وثائقية وسينمائية', 'جودة صوتية محيطية'],
    isVerified: true,
    highlightColor: 'from-red-600/20 to-rose-700/20'
  },
  {
    id: 'tg-netflixllsll',
    name: 'قناة دراما وإثارة ومسلسلات (Netflix & Series)',
    handle: '@netflixllsll',
    url: 'https://t.me/netflixllsll',
    webPreviewUrl: 'https://t.me/s/netflixllsll',
    type: 'channel',
    category: 'series',
    badge: 'مسلسلات وأكشن ',
    description: 'مسلسلات عالمية وعربية مترجمة، مواسم كاملة بدون إعلانات مع سيرفرات سريعة وسهولة التنزيل والمشاهدة.',
    subscribersOrUsers: '+85K عضو نشط',
    featuredContent: ['مواسم كاملة برابط واحد', 'مسلسلات تاريخية ومغامرات', 'دراما وجريمة', 'سيرفرات سحابية دائمة'],
    isVerified: true,
    highlightColor: 'from-purple-600/20 to-indigo-700/20'
  },
  {
    id: 'tg-kkjsiixhhh',
    name: 'سينما النخبة والأفلام الأجنبية المختارة',
    handle: '@kkjsiixhhh',
    url: 'https://t.me/kkjsiixhhh',
    webPreviewUrl: 'https://t.me/s/kkjsiixhhh',
    type: 'channel',
    category: 'movies',
    badge: 'سينما حصرية ',
    description: 'مجموعة مختارة بعناية من أفضل الأفلام السينمائية العالمية، أفلام الإثارة والدراما والغموض بتقييمات عالية.',
    subscribersOrUsers: '+70K عضو نشط',
    featuredContent: ['أفلام هوليوود الحديثة', 'أفلام غموض وإثارة', 'أفلام سينما 1080p FHD', 'مشاهدة بدون إعلانات'],
    isVerified: true,
    highlightColor: 'from-violet-500/20 to-purple-800/20'
  },
  {
    id: 'tg-asia2tv',
    name: 'شبكة ASIA2TV للدراما الكورية والآسيوية',
    handle: '@asia2tv',
    url: 'https://t.me/asia2tv',
    webPreviewUrl: 'https://t.me/s/asia2tv',
    type: 'channel',
    category: 'kdrama',
    badge: 'دراما كورية K-Drama ',
    description: 'المرجع الأول لمسلسلات الدراما الكورية (كيدراما)، المسلسلات الآسيوية، ومسلسلات الكيدراما مترجمة بدقة عالية.',
    subscribersOrUsers: '+110K متابع نشط',
    featuredContent: ['مسلسلات كورية K-Drama', 'طبيب الشبح Ghost Doctor', 'دراما صينية ويابانية', 'ترجمة حصرية وسريعة'],
    isVerified: true,
    highlightColor: 'from-cyan-500/20 to-blue-600/20'
  },
  {
    id: 'tg-saveasbot',
    name: 'بوت SaveAsBot لتحميل الفيديوهات والوسائط',
    handle: '@SaveAsBot',
    url: 'https://t.me/SaveAsBot',
    botStartUrl: 'https://t.me/SaveAsBot?start=media',
    type: 'bot',
    category: 'bots',
    badge: 'بوت تنزيل فوري ',
    description: 'أشهر وأقوى بوت موثق على تيليجرام لتنزيل مقاطع الفيديو، الأفلام، والوسائط بجودة أصلية وبسرعة فائقة.',
    subscribersOrUsers: 'أكثر من 1,000,000 مستخدم',
    featuredContent: ['تنزيل فيديوهات بجودة أصلية', 'استخراج الصوتيات النقية', 'دعم منصات متعددة', 'سرعة استجابة فورية'],
    isVerified: true,
    highlightColor: 'from-emerald-600/20 to-green-800/20'
  },
  {
    id: 'tg-ytbdownbot',
    name: 'بوت YtbDownBot لتحميل الصوتيات والشارات',
    handle: '@YtbDownBot',
    url: 'https://t.me/YtbDownBot',
    botStartUrl: 'https://t.me/YtbDownBot?start=audio',
    type: 'bot',
    category: 'bots',
    badge: 'بوت يوتيوب وصوتيات ',
    description: 'بوت تفاعلي موثوق لتحميل شارات الأنمي والأفلام والأغاني بصيغة MP3 و MP4 بجودة عالية وبدون إعلانات.',
    subscribersOrUsers: 'بوت نشط وسريع',
    featuredContent: ['تحميل بصيغة MP3 صوت نقي', 'تحميل فيديوهات بدقة 1080p', 'روابط سريعة بدون إعلانات', 'سهولة الاستخدام'],
    isVerified: true,
    highlightColor: 'from-red-600/20 to-rose-700/20'
  }
];
